// This file is auto-generated by Supabase CLI
// Run: npm run db:generate-types to update

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type UserRole =
  | 'super_admin'
  | 'company_admin'
  | 'market_manager'
  | 'sales_rep'
  | 'photographer'
  | 'editor'
  | 'qc_reviewer'
  | 'customer'
  | 'support';

export type OrderStatus =
  | 'draft'
  | 'pending_payment'
  | 'confirmed'
  | 'scheduled'
  | 'en_route'
  | 'started'
  | 'completed'
  | 'uploading'
  | 'editing'
  | 'qc_pending'
  | 'qc_failed'
  | 'qc_passed'
  | 'delivered'
  | 'cancelled'
  | 'on_hold';

export type AppointmentStatus =
  | 'scheduled'
  | 'confirmed'
  | 'en_route'
  | 'arrived'
  | 'in_progress'
  | 'completed'
  | 'cancelled'
  | 'no_show'
  | 'rescheduled';

export type QCStatus =
  | 'pending'
  | 'in_progress'
  | 'passed'
  | 'warning'
  | 'failed'
  | 'override_approved';

export type MediaType =
  | 'photo'
  | 'video'
  | 'drone_photo'
  | 'drone_video'
  | 'matterport'
  | 'floor_plan'
  | 'virtual_staging'
  | 'twilight'
  | 'document';

export interface Database {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string;
          name: string;
          slug: string;
          legal_name: string | null;
          tax_id: string | null;
          logo_url: string | null;
          website: string | null;
          phone: string | null;
          email: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          country: string;
          settings: Json;
          features: Json;
          billing_email: string | null;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          quickbooks_company_id: string | null;
          quickbooks_realm_id: string | null;
          hubspot_portal_id: string | null;
          is_active: boolean;
          trial_ends_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          legal_name?: string | null;
          tax_id?: string | null;
          logo_url?: string | null;
          website?: string | null;
          phone?: string | null;
          email?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string;
          settings?: Json;
          features?: Json;
          billing_email?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          is_active?: boolean;
          trial_ends_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['companies']['Insert']>;
      };
      markets: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          slug: string;
          code: string | null;
          city: string;
          state: string;
          country: string;
          timezone: string;
          service_area_geojson: Json | null;
          center_lat: number | null;
          center_lng: number | null;
          radius_miles: number;
          settings: Json;
          pricing_multiplier: number;
          min_lead_time_hours: number;
          max_booking_days_ahead: number;
          operating_hours: Json;
          fly_zones: Json;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          slug: string;
          code?: string | null;
          city: string;
          state: string;
          country?: string;
          timezone: string;
          settings?: Json;
          pricing_multiplier?: number;
          min_lead_time_hours?: number;
          max_booking_days_ahead?: number;
          is_active?: boolean;
        };
        Update: Partial<Database['public']['Tables']['markets']['Insert']>;
      };
      users: {
        Row: {
          id: string;
          company_id: string | null;
          email: string;
          phone: string | null;
          first_name: string;
          last_name: string;
          display_name: string;
          avatar_url: string | null;
          timezone: string | null;
          locale: string;
          notification_preferences: Json;
          is_active: boolean;
          is_verified: boolean;
          verified_at: string | null;
          last_login_at: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          company_id?: string | null;
          email: string;
          phone?: string | null;
          first_name: string;
          last_name: string;
          avatar_url?: string | null;
          timezone?: string | null;
          locale?: string;
          notification_preferences?: Json;
          is_active?: boolean;
          is_verified?: boolean;
          metadata?: Json;
        };
        Update: Partial<Database['public']['Tables']['users']['Insert']>;
      };
      user_roles: {
        Row: {
          id: string;
          user_id: string;
          company_id: string | null;
          market_id: string | null;
          role: UserRole;
          is_primary: boolean;
          granted_by: string | null;
          granted_at: string;
          expires_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          company_id?: string | null;
          market_id?: string | null;
          role: UserRole;
          is_primary?: boolean;
          granted_by?: string | null;
          expires_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['user_roles']['Insert']>;
      };
      customers: {
        Row: {
          id: string;
          company_id: string;
          user_id: string | null;
          email: string;
          phone: string | null;
          first_name: string;
          last_name: string;
          display_name: string;
          business_name: string | null;
          business_type: string | null;
          license_number: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          primary_market_id: string | null;
          billing_email: string | null;
          stripe_customer_id: string | null;
          payment_terms: number;
          credit_limit: number;
          current_balance: number;
          hubspot_contact_id: string | null;
          hubspot_company_id: string | null;
          preferred_photographers: string[] | null;
          preferences: Json;
          lifetime_orders: number;
          lifetime_revenue: number;
          average_order_value: number;
          assigned_sales_rep_id: string | null;
          is_active: boolean;
          is_vip: boolean;
          tags: string[] | null;
          referral_source: string | null;
          referred_by_customer_id: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          user_id?: string | null;
          email: string;
          phone?: string | null;
          first_name: string;
          last_name: string;
          business_name?: string | null;
          business_type?: string | null;
          primary_market_id?: string | null;
          is_active?: boolean;
          is_vip?: boolean;
        };
        Update: Partial<Database['public']['Tables']['customers']['Insert']>;
      };
      photographers: {
        Row: {
          id: string;
          company_id: string;
          user_id: string;
          bio: string | null;
          profile_photo_url: string | null;
          portfolio_url: string | null;
          home_address_line1: string | null;
          home_address_line2: string | null;
          home_city: string | null;
          home_state: string | null;
          home_postal_code: string | null;
          home_lat: number | null;
          home_lng: number | null;
          primary_market_id: string | null;
          service_radius_miles: number;
          skills: string[] | null;
          certifications: Json;
          equipment_notes: string | null;
          has_own_equipment: boolean;
          hourly_rate: number | null;
          per_job_base_rate: number | null;
          mileage_rate: number;
          payment_method: string;
          bank_account_last4: string | null;
          tax_id_type: string | null;
          tax_id_last4: string | null;
          w9_on_file: boolean;
          quickbooks_vendor_id: string | null;
          total_jobs_completed: number;
          average_rating: number;
          total_ratings: number;
          on_time_percentage: number;
          qc_pass_rate: number;
          is_active: boolean;
          is_available: boolean;
          onboarding_completed: boolean;
          onboarding_completed_at: string | null;
          max_daily_jobs: number;
          preferred_job_types: string[] | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          user_id: string;
          bio?: string | null;
          primary_market_id?: string | null;
          skills?: string[] | null;
          is_active?: boolean;
          is_available?: boolean;
        };
        Update: Partial<Database['public']['Tables']['photographers']['Insert']>;
      };
      orders: {
        Row: {
          id: string;
          company_id: string;
          market_id: string;
          order_number: string;
          customer_id: string;
          customer_contact_id: string | null;
          property_id: string;
          status: OrderStatus;
          status_changed_at: string;
          preferred_date: string | null;
          preferred_time_start: string | null;
          preferred_time_end: string | null;
          is_flexible_time: boolean;
          is_rush: boolean;
          rush_fee: number;
          subtotal: number;
          discount_amount: number;
          discount_code: string | null;
          tax_amount: number;
          tax_rate: number;
          rush_fee_amount: number;
          travel_fee: number;
          total: number;
          payment_status: string;
          payment_method: string | null;
          stripe_payment_intent_id: string | null;
          paid_at: string | null;
          expected_delivery_at: string | null;
          actual_delivery_at: string | null;
          delivery_url: string | null;
          delivery_password: string | null;
          source: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          sales_rep_id: string | null;
          commission_rate: number | null;
          coupon_id: string | null;
          referral_id: string | null;
          customer_notes: string | null;
          internal_notes: string | null;
          cancelled_at: string | null;
          cancelled_by: string | null;
          cancellation_reason: string | null;
          cancellation_fee: number;
          metadata: Json;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          market_id: string;
          order_number: string;
          customer_id: string;
          property_id: string;
          status?: OrderStatus;
          preferred_date?: string | null;
          preferred_time_start?: string | null;
          preferred_time_end?: string | null;
          is_rush?: boolean;
        };
        Update: Partial<Database['public']['Tables']['orders']['Insert']>;
      };
      appointments: {
        Row: {
          id: string;
          company_id: string;
          order_id: string;
          scheduled_date: string;
          scheduled_start_time: string;
          scheduled_end_time: string;
          timezone: string;
          estimated_duration_minutes: number;
          actual_duration_minutes: number | null;
          photographer_id: string | null;
          assigned_at: string | null;
          assigned_by: string | null;
          status: AppointmentStatus;
          status_changed_at: string;
          checked_in_at: string | null;
          checked_in_lat: number | null;
          checked_in_lng: number | null;
          checked_out_at: string | null;
          checked_out_lat: number | null;
          checked_out_lng: number | null;
          travel_distance_miles: number | null;
          travel_duration_minutes: number | null;
          en_route_at: string | null;
          arrived_at: string | null;
          customer_confirmed: boolean;
          customer_confirmed_at: string | null;
          photographer_confirmed: boolean;
          photographer_confirmed_at: string | null;
          equipment_checklist: Json;
          equipment_verified: boolean;
          reschedule_count: number;
          last_rescheduled_at: string | null;
          rescheduled_by: string | null;
          reschedule_reason: string | null;
          original_date: string | null;
          original_time: string | null;
          notes: string | null;
          photographer_notes: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          order_id: string;
          scheduled_date: string;
          scheduled_start_time: string;
          scheduled_end_time: string;
          timezone: string;
          estimated_duration_minutes: number;
          photographer_id?: string | null;
          status?: AppointmentStatus;
        };
        Update: Partial<Database['public']['Tables']['appointments']['Insert']>;
      };
      media_assets: {
        Row: {
          id: string;
          company_id: string;
          order_id: string | null;
          deliverable_id: string | null;
          appointment_id: string | null;
          filename: string;
          original_filename: string | null;
          file_extension: string | null;
          mime_type: string | null;
          file_size_bytes: number | null;
          storage_bucket: string;
          storage_path: string;
          public_url: string | null;
          signed_url: string | null;
          signed_url_expires_at: string | null;
          media_type: MediaType;
          width: number | null;
          height: number | null;
          duration_seconds: number | null;
          is_processed: boolean;
          processed_at: string | null;
          thumbnail_url: string | null;
          preview_url: string | null;
          exif_data: Json;
          is_edited: boolean;
          edited_at: string | null;
          edited_by: string | null;
          original_asset_id: string | null;
          edit_version: number;
          qc_status: QCStatus;
          qc_score: number | null;
          qc_notes: string | null;
          qc_issues: Json;
          qc_reviewed_at: string | null;
          qc_reviewed_by: string | null;
          ai_analysis: Json;
          ai_tags: string[] | null;
          ai_description: string | null;
          room_type: string | null;
          scene_type: string | null;
          display_order: number;
          is_featured: boolean;
          is_cover: boolean;
          is_deleted: boolean;
          deleted_at: string | null;
          uploaded_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          order_id?: string | null;
          filename: string;
          storage_bucket: string;
          storage_path: string;
          media_type: MediaType;
          uploaded_by?: string | null;
        };
        Update: Partial<Database['public']['Tables']['media_assets']['Insert']>;
      };
      products: {
        Row: {
          id: string;
          company_id: string;
          category_id: string | null;
          name: string;
          slug: string;
          description: string | null;
          short_description: string | null;
          base_price: number;
          cost: number | null;
          pricing_type: string;
          pricing_tiers: Json | null;
          estimated_duration_minutes: number;
          setup_time_minutes: number;
          thumbnail_url: string | null;
          gallery_urls: string[] | null;
          required_skills: string[] | null;
          required_equipment: string[] | null;
          deliverable_count: number | null;
          deliverable_types: MediaType[] | null;
          turnaround_hours: number;
          available_markets: string[] | null;
          lead_time_hours: number;
          upsell_product_ids: string[] | null;
          addon_product_ids: string[] | null;
          is_active: boolean;
          is_featured: boolean;
          display_order: number;
          meta_title: string | null;
          meta_description: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          slug: string;
          base_price: number;
          is_active?: boolean;
        };
        Update: Partial<Database['public']['Tables']['products']['Insert']>;
      };
      qc_jobs: {
        Row: {
          id: string;
          company_id: string;
          order_id: string;
          upload_job_id: string | null;
          job_type: string;
          status: QCStatus;
          total_assets: number;
          passed_assets: number;
          warning_assets: number;
          failed_assets: number;
          overall_score: number | null;
          started_at: string | null;
          completed_at: string | null;
          assigned_to: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          override_approved: boolean;
          override_by: string | null;
          override_at: string | null;
          override_reason: string | null;
          ai_processed: boolean;
          ai_processed_at: string | null;
          ai_model_version: string | null;
          summary: Json;
          recommendations: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          order_id: string;
          upload_job_id?: string | null;
          job_type?: string;
          status?: QCStatus;
        };
        Update: Partial<Database['public']['Tables']['qc_jobs']['Insert']>;
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_user_company_id: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      has_role: {
        Args: { required_role: UserRole };
        Returns: boolean;
      };
      is_super_admin: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      is_company_admin: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
    };
    Enums: {
      user_role: UserRole;
      order_status: OrderStatus;
      appointment_status: AppointmentStatus;
      qc_status: QCStatus;
      media_type: MediaType;
    };
  };
}
